### ISSUE TITLE
Add Dashboard link

### ISSUE THREAD

**Issue by ckrina** [Lullabot/navigation#16]
### Description 

We should add a new link in the sidebar that links to an future Dashboard we'll create for Drupal core. You can get an overview in the[ Ideas issue in drupal.org.](https://www.drupal.org/project/ideas/issues/3244581).

### Activities in this ticket

- Create a new and independent link (neither inside the Content nor the Administration menus).
- The path for it hasn't been defined yet, so just using either "#" or "/admin" for the `href` value is OK for now.
- The icon can be picked from Figma (the outlined version).

![Image](https://user-images.githubusercontent.com/2225966/251391846-3430e2ed-128c-4a83-bdc9-ec77172f06f6.png)

**Comment by claireristow** [comment]
Hey @sveta1x have you started on this one yet? I have [a PR open](https://github.com/Lullabot/navigation/pull/29) for #22 but I also decided to add the Dashboard link to that one because the HTML was so interconnected. Let me know if that's going to conflict with any work you may have started here.

**Comment by sveta1x** [comment]
@claireristow hi, no, all good you can work on it, I am fully booked on another project right now..

**Comment by claireristow** [comment]
Great thanks Sveta!
