### ISSUE TITLE
Add animations to open / close menus

### ISSUE THREAD

**Issue by mherchel** [Lullabot/navigation#25]

**Comment by mherchel** [comment]
Add open close animations to both icons and the submenus. 

Doing the submenus is tricky, because you can't animate the max-height between `0` and `auto`. There's ways around this, such as 

1. Instead of `display: none` the submenu, use `visibility: hidden` and `position: absolute`. 
2. Doing so, will enable you to use JS to calculate the height of each submenu using something like [offsetHeight](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight).
3. Use JS to add that height as the value of an inline custom property.
4. Animate `max-height` to the value of that custom property

**Comment by baluv3** [comment]
Issue moved here https://www.drupal.org/project/navigation/issues/3374460 and still active. Moving this issue to done.
