### ISSUE TITLE
Convert the User link into a collapsible menu

### ISSUE THREAD

**Issue by ckrina** [Lullabot/navigation#26]
![Image](https://github.com/Lullabot/navigation/assets/1605905/8473cb28-4428-49d6-841d-6ab39947dc5f)

Create a submenu with four submenus:

- Edit
- View profile
- Edit profile
- Log out

**Comment by ckrina** [comment]
This should ideally be done afetr #22

**Comment by claireristow** [comment]
Hey @ckrina are there designs for what these links will look like? Do they "popup" beside the user's picture, show up underneath, etc? Will they have icons like all of the other links above?

**Comment by baluv3** [comment]
Issue moved tohttps://www.drupal.org/project/navigation/issues/3374217 and fixed.
